### ISSUE TITLE
Arrays: .filter()

### ISSUE THREAD

**Issue by eaCe** [Sh4bbY/dojo#1]
Array.filter hinzufügen? 
Kann einen PR erstellen, muss mir aber erst mal die tests ansehen.

**Comment by Sh4bbY** [comment]
du meinst eine Aufgabe hinzufügen in der man ein Array filtern muss?
gute Idee, das fehlt auf jeden Fall noch. kannst gerne einen PR machen 👍

**Comment by eaCe** [comment]
habs natürlich verdaddelt...
